include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/*.gr.dart"
    - "**/generated_plugin_registrant.dart"
    - "build/**"

  errors:
    unused_import: warning
    unnecessary_import: warning

linter:
  rules:
    directives_ordering: true
    combinators_ordering: true
    unnecessary_library_directive: true
    prefer_single_quotes: true
    require_trailing_commas: true
    unnecessary_string_interpolations: true
    unnecessary_const: true
    unnecessary_this: true

formatter:
  page_width: 100
